In [12]:
import pandas as pd
import numpy as np
from sklearn.impute import SimpleImputer

In [13]:
CSV_PATH = r"C:\Users\Admin\Desktop\TANPHAT\Dự án_canhan\TIKTOK_V2\clustering\creator_features_final4.csv"
df = pd.read_csv(CSV_PATH)
print(f"Raw data: {df.shape[0]} rows, {df.shape[1]} cols")

Raw data: 2849 rows, 60 cols

In [14]:
df

,CREATOR_ID,VIDEO_ID,CREATE_TIME,FOLLOWERS,FOLLOWING_COUNT,ENGAGEMENT,TOTAL_LIKES,DIGG_COUNT,VIDEO_COUNT,COLLAB_SCORE,...,VIEW_MEAN,VIEW_STD,VIEW_CV,VIDEO_COUNT_x,VIEW_P90,VIEW_MEAN_V,VIDEO_COUNT_y,VIRAL_MAGNITUDE,MAX_VIRAL_STRENGTH,AVG_VIRAL_STRENGTH
0,._.ehe23,7587372080832826645,2025-12-24 17:38:52,34700,31,10.26,2400000,16800,396,79.6,...,10210.974359,9020.530159,0.883415,39.0,20840.0,10210.974359,39.0,2.040941,3.858594,1.0
1,.hoang.kha.71,7586971702626684180,2025-12-23 18:15:00,283800,57,10.76,4000000,15000,1273,74.0,...,8352.875776,20107.036653,2.407199,322.0,18900.0,8352.875776,322.0,2.262694,26.505841,1.0
2,.k.c.c5,7587269967213612295,2025-12-24 11:02:37,104600,69,4.00,1900000,112400,1484,84.2,...,61276.392442,156538.152516,2.554624,344.0,162410.0,61276.392442,344.0,2.650450,29.375097,1.0
3,.qkhanh1403,7603192756286000392,2026-02-05 08:51:09,619400,10,11.20,25100000,6234,1729,81.0,...,44473.784314,63516.916866,1.428188,51.0,108500.0,44473.784314,51.0,2.439639,7.415605,1.0
4,.siudangiu06,7588104760432315666,2025-12-26 17:02:04,91900,113,11.09,3400000,14500,386,77.2,...,18573.219512,35320.956860,1.901714,41.0,53800.0,18573.219512,41.0,2.896644,10.649742,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2844,ztimu_,7593769977702862101,2026-01-10 23:26:00,21600,404,10.56,967900,3950,28,74.8,...,49633.333333,16976.846979,0.342045,3.0,63660.0,49633.333333,3.0,1.282606,1.392210,1.0
2845,zuohang2006.official,7587801859209858325,2025-12-25 21:26:35,665600,201,7.09,9100000,2657,1656,77.3,...,135774.972569,925584.026163,6.817044,401.0,90600.0,135774.972569,401.0,0.667281,95.010146,1.0
2846,zybithanhtruc,7589498335032053000,2025-12-30 11:09:53,3600000,49,5.18,38400000,4325,804,75.3,...,70038.571429,107027.197689,1.528118,21.0,149200.0,70038.571429,21.0,2.130255,6.096641,1.0
2847,zynanh15,7587996773843553554,2025-12-26 10:02:59,179600,18,15.54,7700000,18300,759,81.0,...,64381.364706,238490.831918,3.704346,85.0,101880.0,64381.364706,85.0,1.582445,32.618134,1.0
2848,zyycute._,7589867129340431624,2025-12-31 11:00:53,99900,149,8.24,1700000,7357,310,75.8,...,21033.000000,20550.977535,0.977083,18.0,39790.0,21033.000000,18.0,1.891789,3.832073,1.0

In [15]:
print(df.shape)
print(df.columns.tolist())
df.describe(percentiles=[0.5, 0.9, 0.99]).T

(2849, 60)
['CREATOR_ID', 'VIDEO_ID', 'CREATE_TIME', 'FOLLOWERS', 'FOLLOWING_COUNT', 'ENGAGEMENT', 'TOTAL_LIKES', 'DIGG_COUNT', 'VIDEO_COUNT', 'COLLAB_SCORE', 'VIEW_COUNT', 'LIKE_COUNT', 'COMMENT_COUNT', 'SHARE_COUNT', 'SAVE_COUNT', 'VQSCORE', 'BITRATE', 'CATEGORY_TYPE', 'CATEGORY_y', 'PRICE_NUM', 'HAS_SHOP_LINK', 'hour', 'CREATOR_TIER', 'DAY_OF_WEEK', 'MEAN_LIKES_3M', 'P90_LIKES_3M', 'MAX_LIKES_3M', 'MEAN_COMMENTS_3M', 'P90_COMMENTS_3M', 'MAX_COMMENTS_3M', 'MEAN_SHARES_3M', 'P90_SHARES_3M', 'MAX_SHARES_3M', 'MEAN_SAVES_3M', 'P90_SAVES_3M', 'MAX_SAVES_3M', 'MEAN_VIEWS_3M', 'P90_VIEWS_3M', 'MAX_VIEWS_3M', 'VIDEO_COUNT_3M_x', 'MEAN_VIEWS_RATE_3M', 'MEAN_LIKE_RATE_3M', 'MEAN_COMMENT_RATE_3M', 'MEAN_SHARE_RATE_3M', 'MEAN_SAVE_RATE_3M', 'VIDEO_COUNT_3M_y', 'unique_days', 'AVG_POST_GAP', 'VIDEOS_PER_WEEK', 'POSTING_CONSISTENCY', 'VIEW_MEAN', 'VIEW_STD', 'VIEW_CV', 'VIDEO_COUNT_x', 'VIEW_P90', 'VIEW_MEAN_V', 'VIDEO_COUNT_y', 'VIRAL_MAGNITUDE', 'MAX_VIRAL_STRENGTH', 'AVG_VIRAL_STRENGTH']

,count,mean,std,min,50%,90%,99%,max
VIDEO_ID,2849.0,7.590238e+18,5.529586e+15,7.561749e+18,7.588114e+18,7.596236e+18,7.613427e+18,7.620368e+18
FOLLOWERS,2849.0,4.324735e+05,1.125925e+06,4.864000e+03,1.503000e+05,9.295800e+05,4.612000e+06,2.120000e+07
FOLLOWING_COUNT,2849.0,3.337992e+02,1.065541e+03,0.000000e+00,6.100000e+01,6.380000e+02,6.638680e+03,1.000000e+04
ENGAGEMENT,2849.0,5.325184e+00,4.815198e+00,1.200000e-01,3.960000e+00,1.101600e+01,1.904640e+01,9.416000e+01
TOTAL_LIKES,2849.0,1.152691e+07,3.106855e+07,1.712000e+03,3.200000e+06,2.450000e+07,1.662880e+08,4.899000e+08
DIGG_COUNT,2849.0,1.672767e+04,3.818599e+04,0.000000e+00,4.729000e+03,4.168000e+04,1.773120e+05,5.543000e+05
VIDEO_COUNT,2849.0,7.193229e+02,1.394927e+03,1.000000e+00,3.740000e+02,1.489200e+03,6.139440e+03,3.590000e+04
COLLAB_SCORE,2809.0,7.840456e+01,5.917600e+00,6.120000e+01,7.720000e+01,8.782000e+01,9.440000e+01,9.880000e+01
VIEW_COUNT,2849.0,3.595335e+05,1.843914e+06,0.000000e+00,4.350000e+04,5.972000e+05,5.452000e+06,5.750000e+07
LIKE_COUNT,2849.0,1.356582e+04,6.977113e+04,0.000000e+00,1.290000e+03,2.312000e+04,2.188360e+05,1.600000e+06
COMMENT_COUNT,2849.0,1.703131e+02,9.216107e+02,0.000000e+00,2.600000e+01,2.510000e+02,2.310160e+03,2.060000e+04
SHARE_COUNT,2849.0,2.357714e+03,2.100135e+04,0.000000e+00,4.300000e+01,2.311200e+03,3.866400e+04,7.591000e+05
SAVE_COUNT,2849.0,1.083046e+03,7.545150e+03,0.000000e+00,8.100000e+01,1.562600e+03,1.539712e+04,2.959490e+05
VQSCORE,2849.0,6.651256e+01,9.343603e+00,0.000000e+00,6.799000e+01,7.368200e+01,7.758000e+01,8.619000e+01
BITRATE,2849.0,1.241911e+06,6.187241e+05,8.712400e+04,1.116554e+06,2.029227e+06,3.451541e+06,4.116054e+06
CATEGORY_TYPE,2849.0,1.115219e+02,7.352598e+00,1.000000e+02,1.110000e+02,1.200000e+02,1.200000e+02,1.200000e+02
PRICE_NUM,2849.0,1.309345e+07,1.110657e+08,1.000000e+00,2.000000e+06,1.200000e+07,1.200000e+08,2.631000e+09
HAS_SHOP_LINK,2849.0,1.544402e-01,3.614336e-01,0.000000e+00,0.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00
hour,2849.0,1.487539e+01,4.873353e+00,0.000000e+00,1.600000e+01,2.100000e+01,2.300000e+01,2.300000e+01
DAY_OF_WEEK,2849.0,3.191646e+00,1.530743e+00,0.000000e+00,3.000000e+00,5.000000e+00,6.000000e+00,6.000000e+00
MEAN_LIKES_3M,2846.0,9.368003e+03,2.382676e+04,0.000000e+00,3.254198e+03,2.181195e+04,8.731685e+04,8.419000e+05
P90_LIKES_3M,2846.0,2.001495e+04,4.276267e+04,0.000000e+00,6.255900e+03,5.061500e+04,2.014290e+05,8.419000e+05
MAX_LIKES_3M,2846.0,8.810565e+04,1.849736e+05,0.000000e+00,3.090000e+04,2.169500e+05,7.829300e+05,3.600000e+06
MEAN_COMMENTS_3M,2846.0,1.187234e+02,4.020867e+02,0.000000e+00,4.548716e+01,2.501459e+02,1.109959e+03,1.538183e+04
P90_COMMENTS_3M,2846.0,2.445794e+02,1.149134e+03,0.000000e+00,8.000000e+01,5.058000e+02,2.362875e+03,5.429000e+04
MAX_COMMENTS_3M,2846.0,1.484447e+03,1.000100e+04,0.000000e+00,3.315000e+02,2.977500e+03,1.547500e+04,4.851000e+05
MEAN_SHARES_3M,2846.0,1.809352e+03,7.240711e+03,0.000000e+00,2.329826e+02,3.310500e+03,2.789629e+04,1.817762e+05
P90_SHARES_3M,2846.0,3.667184e+03,1.546229e+04,0.000000e+00,3.824500e+02,6.281550e+03,6.289500e+04,3.802000e+05
MAX_SHARES_3M,2846.0,2.972335e+04,1.636333e+05,0.000000e+00,2.926000e+03,5.585000e+04,4.297350e+05,6.600000e+06
MEAN_SAVES_3M,2846.0,6.954169e+02,2.193666e+03,0.000000e+00,2.343228e+02,1.481115e+03,6.495950e+03,6.786450e+04
P90_SAVES_3M,2846.0,1.498991e+03,4.061788e+03,0.000000e+00,4.582500e+02,3.259500e+03,1.573904e+04,1.207129e+05
MAX_SAVES_3M,2846.0,6.881426e+03,1.618981e+04,0.000000e+00,2.285000e+03,1.677100e+04,7.238055e+04,2.959490e+05
MEAN_VIEWS_3M,2846.0,2.416371e+05,6.020347e+05,0.000000e+00,1.019151e+05,5.701551e+05,1.987320e+06,2.037500e+07
P90_VIEWS_3M,2846.0,5.026846e+05,1.161772e+06,0.000000e+00,1.792450e+05,1.200000e+06,4.100000e+06,3.524000e+07
MAX_VIEWS_3M,2846.0,2.458554e+06,4.899625e+06,0.000000e+00,9.423000e+05,5.900000e+06,2.261000e+07,6.860000e+07
VIDEO_COUNT_3M_x,2846.0,7.240513e+01,9.730172e+01,1.000000e+00,3.900000e+01,1.750000e+02,5.140000e+02,5.600000e+02
MEAN_VIEWS_RATE_3M,2846.0,2.652824e+00,9.961376e+00,0.000000e+00,6.326791e-01,5.908304e+00,3.068275e+01,3.776435e+02
MEAN_LIKE_RATE_3M,2845.0,5.005938e-02,6.697222e-02,9.936982e-04,3.575375e-02,9.392698e-02,2.121872e-01,1.367201e+00
MEAN_COMMENT_RATE_3M,2845.0,1.570836e-03,5.672966e-03,0.000000e+00,6.997948e-04,2.571988e-03,1.482237e-02,1.819391e-01
MEAN_SHARE_RATE_3M,2845.0,5.036502e-03,2.109318e-02,0.000000e+00,1.824990e-03,9.900111e-03,4.722702e-02,9.159088e-01
MEAN_SAVE_RATE_3M,2845.0,4.220343e-03,1.040569e-02,3.563647e-05,2.379596e-03,8.110671e-03,2.832185e-02,4.010188e-01
VIDEO_COUNT_3M_y,2846.0,7.240513e+01,9.730172e+01,1.000000e+00,3.900000e+01,1.750000e+02,5.140000e+02,5.600000e+02
unique_days,2846.0,3.573963e+01,2.453341e+01,1.000000e+00,3.100000e+01,7.400000e+01,8.900000e+01,9.000000e+01
AVG_POST_GAP,2806.0,3.650057e+00,5.353852e+00,8.337488e-03,1.983692e+00,8.072374e+00,2.732664e+01,7.033561e+01
VIDEOS_PER_WEEK,2846.0,5.569625e+00,7.484747e+00,7.692308e-02,3.000000e+00,1.346154e+01,3.953846e+01,4.307692e+01
POSTING_CONSISTENCY,2846.0,3.927432e-01,2.695979e-01,1.098901e-02,3.406593e-01,8.131868e-01,9.780220e-01,9.890110e-01
VIEW_MEAN,2846.0,2.416371e+05,6.020347e+05,0.000000e+00,1.019151e+05,5.701551e+05,1.987320e+06,2.037500e+07
VIEW_STD,2806.0,4.340605e+05,8.449737e+05,0.000000e+00,1.779893e+05,1.010441e+06,3.747380e+06,1.411421e+07
VIEW_CV,2806.0,1.933243e+00,1.218737e+00,0.000000e+00,1.660821e+00,3.390002e+00,6.343804e+00,1.484748e+01
VIDEO_COUNT_x,2846.0,7.240513e+01,9.730172e+01,1.000000e+00,3.900000e+01,1.750000e+02,5.140000e+02,5.600000e+02
VIEW_P90,2846.0,5.026846e+05,1.161772e+06,0.000000e+00,1.792450e+05,1.200000e+06,4.100000e+06,3.524000e+07
VIEW_MEAN_V,2846.0,2.416371e+05,6.020347e+05,0.000000e+00,1.019151e+05,5.701551e+05,1.987320e+06,2.037500e+07
VIDEO_COUNT_y,2846.0,7.240513e+01,9.730172e+01,1.000000e+00,3.900000e+01,1.750000e+02,5.140000e+02,5.600000e+02
VIRAL_MAGNITUDE,2846.0,1.998507e+00,6.824333e-01,0.000000e+00,2.007060e+00,2.832641e+00,3.764800e+00,5.260344e+00
MAX_VIRAL_STRENGTH,2846.0,1.298999e+01,1.787471e+01,0.000000e+00,7.972368e+00,2.726805e+01,8.094832e+01,3.368751e+02
AVG_VIRAL_STRENGTH,2846.0,9.996486e-01,1.874488e-02,0.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00

In [16]:

FEATURE_COLS = [
    'CREATOR_ID', 'VIEW_P90', 'MAX_VIEWS_3M',
    # Scale & reach
    "FOLLOWERS",  "VIDEO_COUNT", "VIDEO_COUNT_3M_x",

    # View performance
    "VIEW_STD", "VIEW_CV", "VIEW_MEAN_V", 
    # Likes / Comments / Shares / Saves
    "MEAN_LIKES_3M",  "MAX_LIKES_3M",
    "MEAN_COMMENTS_3M",  "MAX_COMMENTS_3M",
    "MEAN_SHARES_3M",  "MAX_SHARES_3M",
    "MEAN_SAVES_3M",  "MAX_SAVES_3M",

    # Engagement rates
    "MEAN_VIEWS_RATE_3M", "MEAN_LIKE_RATE_3M",
    "MEAN_COMMENT_RATE_3M", "MEAN_SHARE_RATE_3M", "MEAN_SAVE_RATE_3M",

    # Posting behavior
    "AVG_POST_GAP", "POSTING_CONSISTENCY", "VIDEOS_PER_WEEK",
    
    # Virality & profile
     "MAX_VIRAL_STRENGTH", "COLLAB_SCORE", "VIRAL_MAGNITUDE"
]

In [17]:

# --- Cleaning ---
df = df[df["VIDEO_COUNT_x"].notna()]          # drop inactive creators (no videos)
df = df[df["CREATOR_ID"] != "nhuhexii"]       # drop anomalous creator

# Targeted NA fills
df["VIEW_STD"]    = df["VIEW_STD"].fillna(0)                          # 1 video → no variance
df["VIEW_CV"]     = df["VIEW_CV"].fillna(0)
df["AVG_POST_GAP"] = df["AVG_POST_GAP"].fillna(df["AVG_POST_GAP"].mean())  # 1 video → use mean
df["COLLAB_SCORE"] = df["COLLAB_SCORE"].fillna(df["COLLAB_SCORE"].mean())  # 1 video → use mean

In [18]:
remaining_na = df.isna().sum()
remaining_na = remaining_na[remaining_na > 0]
print("No remaining NAs" if remaining_na.empty else f"Remaining NAs:\n{remaining_na}")

No remaining NAs

In [19]:
# --- Select & validate features ---
df = df[FEATURE_COLS].copy()
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2845 entries, 0 to 2848
Data columns (total 28 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   CREATOR_ID            2845 non-null   object
 1   VIEW_P90              2845 non-null   float64
 2   MAX_VIEWS_3M          2845 non-null   float64
 3   FOLLOWERS             2845 non-null   int64
 4   VIDEO_COUNT           2845 non-null   int64
 5   VIDEO_COUNT_3M_x      2845 non-null   float64
 6   VIEW_STD              2845 non-null   float64
 7   VIEW_CV               2845 non-null   float64
 8   VIEW_MEAN_V           2845 non-null   float64
 9   MEAN_LIKES_3M         2845 non-null   float64
 10  MAX_LIKES_3M          2845 non-null   float64
 11  MEAN_COMMENTS_3M      2845 non-null   float64
 12  MAX_COMMENTS_3M       2845 non-null   float64
 13  MEAN_SHARES_3M        2845 non-null   float64
 14  MAX_SHARES_3M         2845 non-null   float64
 15  MEAN_SAVES_3M         2845 non-null   float64
 16  MAX_SAVES_3M          2845 non-null   float64
 17  MEAN_VIEWS_RATE_3M    2845 non-null   float64
 18  MEAN_LIKE_RATE_3M     2845 non-null   float64
 19  MEAN_COMMENT_RATE_3M  2845 non-null   float64
 20  MEAN_SHARE_RATE_3M    2845 non-null   float64
 21  MEAN_SAVE_RATE_3M     2845 non-null   float64
 22  AVG_POST_GAP          2845 non-null   float64
 23  POSTING_CONSISTENCY   2845 non-null   float64
 24  VIDEOS_PER_WEEK       2845 non-null   float64
 25  MAX_VIRAL_STRENGTH    2845 non-null   float64
 26  COLLAB_SCORE          2845 non-null   float64
 27  VIRAL_MAGNITUDE       2845 non-null   float64
dtypes: float64(25), int64(2), object(1)
memory usage: 644.6+ KB

In [20]:
df = df.drop(columns=[ "MAX_LIKES_3M",'VIEW_P90', 'COLLAB_SCORE', "MEAN_VIEWS_RATE_3M", "MEAN_LIKE_RATE_3M", "MEAN_COMMENT_RATE_3M", "MEAN_SHARE_RATE_3M", "MEAN_SAVE_RATE_3M","MAX_COMMENTS_3M",
      "MAX_SHARES_3M",
      "MAX_SAVES_3M","MAX_VIEWS_3M"
], errors="ignore")

In [21]:
print(df.columns.tolist())

['CREATOR_ID', 'FOLLOWERS', 'VIDEO_COUNT', 'VIDEO_COUNT_3M_x', 'VIEW_STD', 'VIEW_CV', 'VIEW_MEAN_V', 'MEAN_LIKES_3M', 'MEAN_COMMENTS_3M', 'MEAN_SHARES_3M', 'MEAN_SAVES_3M', 'AVG_POST_GAP', 'POSTING_CONSISTENCY', 'VIDEOS_PER_WEEK', 'MAX_VIRAL_STRENGTH', 'VIRAL_MAGNITUDE']

In [23]:
df.to_csv("feature_for_clustering_final.csv", index=False)